<?php

namespace App\Tests;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class CSVManagerServiceTest extends KernelTestCase
{
    private static $CSV;

    private static $PATH_TO_FILE = "/tests/csv/test.csv";

    private $header = "title,description,link,guid,pubDate,creator";

    public static function setUpBeforeClass()
    {
        self::$kernel = static::createKernel();
        self::$kernel->boot();
        self::$container = self::$kernel->getContainer();
        self::$CSV = self::$container->get('csv.manager');
    }

    public function testWritingDataInAppendModeWhenFileNotExists()
    {
        $data = self::$CSV->getArrayOfFeedObjects('http://feeds.bbci.co.uk/news/world/rss.xml');
        self::$CSV->writeToCSVFile(self::$PATH_TO_FILE, $data, 'a');

        $content = file_get_contents(self::$kernel->getProjectDir() . self::$PATH_TO_FILE);
        $index = strpos($content, $this->header);
        $this->assertEquals(0, $index);
    }

    public function testWritingDataInAppendModeWhenFileExists()
    {
        $data = self::$CSV->getArrayOfFeedObjects('http://feeds.bbci.co.uk/news/world/rss.xml');
        self::$CSV->writeToCSVFile(self::$PATH_TO_FILE, $data, 'a');
        $content = file_get_contents(self::$kernel->getProjectDir() . self::$PATH_TO_FILE);

        $count = substr_count($content, $this->header);

        $this->assertEquals(1, $count);
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
        // delete to see the file
        //unlink(self::$kernel->getProjectDir() . self::$PATH_TO_FILE);
    }

    //is that necessary to test OverwriteMode?
}
